name: Backend CI

on:
  push:
    branches: ["master", "develop", "feat/*"]
  pull_request:
    branches: ["master", "develop", "feat/*"]

jobs:
  validate-backend:
    name: Validate .NET Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore DIMS-Backend.csproj

      - name: Build project
        run: dotnet build DIMS-Backend.csproj --no-restore -c Release

      - name: Run Unit Tests
        run: |
          dotnet test ./tests/DIMS-Backend.Tests.csproj --filter "FullyQualifiedName~DIMS_Backend.Tests.Unit" --logger "trx;LogFileName=unit_test_results.trx" --results-directory ./TestResults /p:CollectCoverage=true /p:CoverletOutput=./TestResults/unit_coverage.xml /p:CoverletOutputFormat=cobertura

      - name: Run Behavior Tests
        run: |
          dotnet test ./tests/DIMS-Backend.Tests.csproj --filter "FullyQualifiedName~DIMS_Backend.Tests.Behavior" --logger "trx;LogFileName=behavior_test_results.trx" --results-directory ./TestResults /p:CollectCoverage=true /p:CoverletOutput=./TestResults/behavior_coverage.xml /p:CoverletOutputFormat=cobertura

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: ./TestResults
